version: "3.8"

services:
  web:
    build: ./src
    container_name: fastapi-app
    command: bash -c "/usr/src/app/wait-for-it.sh --timeout=0 postgres:5432 && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
volumes:
  postgres_data:
